nonzero_digits = '|'.join(str(n) for n in range(1, 10))
digits = '|'.join(str(n) for n in range(0, 10))
letters = '|'.join(chr(n) for n in range(ord('a'), ord('z') + 1))
cap_letters = '|'.join(chr(n) for n in range(ord('A'), ord('Z') + 1))
letters = cap_letters + '|' + letters
no_first_zero = f'({nonzero_digits})*|(({nonzero_digits})(0)*)'
lexer_table = [
    ('num', f'{no_first_zero}|(({no_first_zero})*|(0))(.)({digits})*'),
    ('for', 'for'),
    ('foreach', 'foreach'),
    ('while', 'while'),
    ('range', 'range'),
    ('if', 'if'),
    ('else', 'else'),
    ('elif', 'elif'),
    ('space', ' *'),

    ('=', '='),
    (':=', ':='),
    ('*', '\\*'),
    ('/', '/'),
    ('//', '//'),
    ('^', '^'),
    ('+', '+'),
    ('-', '-'),
    ('<', '<'),
    ('<=', '<='),
    ('>', '>'),
    ('>=', '>='),
    ('==', '=='),
    ('!=', '!='),
    ('&', '&'),
    ('|', '\\|'),
    ('!', '!'),
    ('@', '@'),
    ('||', '\\||'),
    ('**', '\\**'),
    ('sqrt', 'sqrt'),
    ('sin', 'sin'),
    ('cos', 'cos'),
    ('exp', 'exp'),
    ('log', 'log'),
    ('rand', 'rand'),

    ('Number', 'Number'),
    ('Object', 'Object'),
    ('Boolean', 'Boolean'),
    ('lit_string', f'"( )*({letters})*( )*({letters})*( )*"'),
    ('false', 'false'),
    ('true', 'true'),

    ('let', 'let'),
    ('in', 'in'),
    ('print', 'print'),
    ('size', 'size'),
    ('function', 'function'),
    ('new', 'new'),
    ('type', 'type'),
    ('self', 'self'),
    ('inherits','inherits'),
    ('protocol', 'protocol'),
    ('extends', 'extends'),
    ('as', 'as'),
    ('is', 'is'),
    ('=>', '=>'),
    ('.', '.'),
    (':', ':'),
    (';', ';'),
    (',', ','),
    ('(', '\\('),
    (')', '\\)'),
    ('{', '{'),
    ('}', '}'),
    ('[', '['),
    (']', ']'),
    ('id', f'({letters})({letters}|0|{nonzero_digits})*')
]